fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

pages:
    type:     rest
    resource: AppBundle\Controller\PageController

fos_rest:
    type: rest
    resource: routing_api.yml

users:
    type:     rest
    resource: AppBundle\Controller\UserController
