# FOSRest Routing
users:
    type: rest
    resource: AppBundle\Controller\UserController

pages:
    type: rest
    resource: AppBundle\Controller\PageController

# revisions:
#     type: rest
#     resource: AppBundle\Controller\PageRevisionController

# ratings:
#     type: rest
#     resource: AppBundle\Controller\RatingController